"""ping add created_by

Revision ID: c64bd2da16b1
Revises: cac46612711f
Create Date: 2025-09-10 08:42:14.863336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64bd2da16b1'
down_revision: Union[str, Sequence[str], None] = 'cac46612711f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ping', sa.Column('created_by', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ping', 'created_by')
    # ### end Alembic commands ###
